INSERT INTO Etnia (codigo, nombre)
VALUES ('00', 'No aplica'),
 ('01', 'Achacua'),
 ('02', 'Amorúa'),
 ('03', 'Amorúa'),
 ('04', 'Indoque o Andoque'),
 ('05', 'Arhuaco (IJKA)'),
('06', 'Awa (CUAIKER)'),
('07', 'Barea'),
('08', 'Barazana'),
('09', 'Barí (Motilon)'),
('10', 'Betoye'),
('11', 'Cabiyarí o Kawiyari'),
('12', 'Carapana'),
('13', 'Carijona o Karijona'),
('14', 'Chimilia '),
('15', 'Chiricoa'),
('16', 'Cocama'),
('17', 'Coconudo'),
('18', 'Cofpán o Kofán'),
('19', 'Piajos'),
('20', 'Cubeo o Kubeo');